# This workflow reuses the openHIE GitHub action for building IGs
# Initial idea by Carl Leitner, developed by Elliot Silver, available from: https://www.argentixinfo.com/archives/156
# Change log:
# v0.1.0
# 2021-06-18: publish default branches to / , other branches branches/<branch>
# 2021-11-26: reusable workflow

name: GitHub Pages build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for any branch
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches-ignore:
      - 'gh-pages'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tx:
        description: 'Optional Custom terminology server URL'
        required: false
      do_dak:
        description: 'Enable DAK preprocessing and postprocessing'
        required: false
        type: boolean
        default: true

jobs:
  # This workflow contains a single job called "build"
  call_build: 
    uses: WorldHealthOrganization/smart-base/.github/workflows/ghbuild.yml@main
